# Generated by Django 4.1.4 on 2023-01-15 09:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('facultyID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('facultyName', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('HOD', 'HOD'), ('Other', 'Other')], max_length=10)),
                ('departmentName', models.CharField(max_length=20)),
                ('facultyAge', models.DateField()),
                ('facultyEmail', models.EmailField(max_length=254)),
                ('facultyGender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('facultyPhone', models.CharField(max_length=10, unique=True)),
                ('accountPassword', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('requestFrom', models.CharField(max_length=50)),
                ('accept', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=10)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('requestTo', models.CharField(max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requestToID', models.ManyToManyField(to='projects2.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('ratingName', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ratingComments', models.TextField(max_length=300)),
                ('ratingStars', models.CharField(blank=True, choices=[('up', 'Up vote'), ('down', 'Down Vote')], max_length=10, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ratingID', models.ManyToManyField(to='projects2.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postTime', models.DateTimeField(auto_now_add=True)),
                ('postCategory', models.CharField(choices=[('Conference', 'Conference'), ('Journal', 'Journal')], max_length=50)),
                ('postSnaps', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('postTags', models.CharField(blank=True, max_length=200, null=True)),
                ('postID', models.ManyToManyField(max_length=20, to='projects2.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('facultyName', models.CharField(max_length=30)),
                ('facultyDept', models.CharField(max_length=20)),
                ('journalID', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('journalName', models.CharField(max_length=50)),
                ('journalISSN', models.CharField(max_length=10)),
                ('journalArticle', models.ImageField(blank=True, null=True, upload_to='')),
                ('UGCListed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20)),
                ('journalNationality', models.CharField(max_length=60)),
                ('facultyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects2.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventLocation', models.TextField(max_length=500)),
                ('eventName', models.CharField(max_length=200)),
                ('eventDate', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eventID', models.ManyToManyField(max_length=30, to='projects2.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('facultyName', models.CharField(max_length=30)),
                ('facultyDept', models.CharField(max_length=20)),
                ('conferenceID', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('conferenceName', models.CharField(max_length=50)),
                ('conferenceDOI', models.CharField(max_length=30)),
                ('conferenceArticle', models.ImageField(blank=True, null=True, upload_to='')),
                ('UGCListed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200)),
                ('conferenceNationality', models.CharField(max_length=60)),
                ('facultyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects2.faculty')),
            ],
        ),
    ]
