# Generated by Django 4.1.4 on 2023-01-15 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='RequestPublications',
        ),
    ]
