# Generated by Django 4.1.4 on 2023-01-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects2', '0002_rename_request_requestpublications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestpublications',
            name='requestToID',
        ),
        migrations.AddField(
            model_name='conference',
            name='rating_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='requestToID',
            field=models.ManyToManyField(to='projects2.requestpublications'),
        ),
        migrations.AddField(
            model_name='post',
            name='ratings',
            field=models.ManyToManyField(blank=True, null=True, to='projects2.rating'),
        ),
    ]
