# Generated by Django 4.1.5 on 2023-01-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects2', '0003_remove_requestpublications_requesttoid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='rating_total',
        ),
        migrations.AddField(
            model_name='conference',
            name='ratingTotal',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
