# Generated by Django 4.1.5 on 2023-01-15 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects2', '0004_remove_conference_rating_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='facultyID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects2.faculty'),
        ),
    ]
