# Generated by Django 4.1.5 on 2023-01-15 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects2', '0005_alter_conference_facultyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventID',
            field=models.ManyToManyField(blank=True, max_length=30, null=True, to='projects2.faculty'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='facultyID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects2.faculty'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postID',
            field=models.ManyToManyField(blank=True, max_length=20, null=True, to='projects2.faculty'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='ratingID',
            field=models.ManyToManyField(blank=True, null=True, to='projects2.faculty'),
        ),
    ]
